### PR TITLE
fix: ensure abort interrupts running queries

### LINKED ISSUE #1173: Expected Behavior of Abort with the AWS JDBC Wrapper
I'm developing an application that connects to PostgreSQL via JDBC using Spring Boot and HikariCP.

When attempting to stop the application (sending SIGINT) while a long-running query is active, it seems that HikariCP waits for the query to complete before aborting the connection. This behavior appears to be related to the AWS JDBC Wrapper's implementation:
(https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/util/WrapperUtils.java#L186)

In contrast, when using only the standard PostgreSQL driver, the connection is forcibly terminated even if a long-running query is in progress.

Question:
Is there a configuration or method to avoid this behavior?
According to the java.sql.Connection#abort specification, the connection should be forcibly terminated.

Thank you.

### PR DESCRIPTION
**Pull request by aaron-congo**
### Description
- fixes #1173 
- abort was not interrupting queries because the plugin manager was locked during query execution and abort was not included in ASYNCHRONOUS_METHODS. This PR fixes this problem by allowing abort to be executed asynchronously
- after allowing asynchronous abort, the exception triggered by abort was triggering failover. To avoid this, closedExplicitly is set when abort is called and checked in shouldExceptionTriggerConnectionSwitch

### By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: wrapper/src/main/java/software/amazon/jdbc/util/AsynchronousMethodsHelper.java [hunk 1]
```diff
@@ -22,6 +22,7 @@
 public class AsynchronousMethodsHelper {
   public static final List<String> ASYNCHRONOUS_METHODS = Arrays.asList(
       "Statement.cancel",
-      "PreparedStatement.cancel"
+      "PreparedStatement.cancel",
+      "Connection.abort"
```
Comment (aaron-congo) [inline wrapper/src/main/java/software/amazon/jdbc/util/AsynchronousMethodsHelper.java:26]: Should Connection.close be added here as well?

Comment (sergiyvamz) [reply wrapper/src/main/java/software/amazon/jdbc/util/AsynchronousMethodsHelper.java:26]: No, I'd keep "abort" in the list, not "close".

**Review by sergiyvamz — APPROVED** [review]
